name: Patch VBMeta

on:
  workflow_dispatch:
    inputs:
      ARCHITECTURE:
        description: 'Architecture'
        required: true
        default: 'x86_64'
        type: choice
        options:- الاسم: ذاكرة التخزين المؤقت
  الاستخدامات: actions/cache@v4.2.4
  مع:
    # قائمة بالملفات والدلائل وأنماط الأحرف البدل لتخزينها مؤقتًا واستعادتها
    طريق: 
    # مفتاح صريح لاستعادة ذاكرة التخزين المؤقت وحفظها
    مفتاح: 
    سلسلة مرتبة متعددة الأسطر تسرد المفاتيح المطابقة للبادئة، والتي تُستخدم لاستعادة ذاكرة التخزين المؤقت القديمة في حال عدم حدوث أي إصابة للمفتاح. ملاحظة: `cache-hit` تُرجع القيمة False في هذه الحالة.
    استعادة المفاتيح: # اختياري
    # حجم الكتلة المستخدمة لتقسيم الملفات الكبيرة أثناء التحميل، بالبايت
    حجم الجزء المرفوع: # اختياري
    # قيمة منطقية اختيارية عند تمكينها، تسمح لمشغلي Windows بحفظ أو استعادة ذاكرة التخزين المؤقت التي يمكن استعادتها أو حفظها على منصات أخرى على التوالي
    enableCrossOsArchive: # اختياري، الافتراضي هو خطأ
    # فشل سير العمل إذا لم يتم العثور على إدخال ذاكرة التخزين المؤقت
    fail-on-cache-miss: # اختياري، الافتراضي هو false
    # تحقق مما إذا كان إدخال ذاكرة التخزين المؤقت موجودًا للمدخلات المحددة (المفتاح، مفاتيح الاستعادة) دون تنزيل ذاكرة التخزين المؤقت
    البحث فقط: # اختياري، الافتراضي هو خطأ
    # قم بتشغيل خطوة النشر لحفظ ذاكرة التخزين المؤقت حتى في حالة فشل خطوة أخرى قبل ذلك
    حفظ دائمًا: # اختياري، الافتراضي هو خطأ
           
        - x86_64
        - x86
        - arm64-v8a
        - armaebi-v7a

permissions:
  contents: write

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    steps:
 
    - name: Check Out
      uses: actions/checkout@v3.1.0
      
    - name: Operating System Information
      run: |
        uname -a
        
    - name: Patch File Information
      run: |
        file ${{ github.event.inputs.ARCHITECTURE }}/vbmeta-disable-verification
        
    - name: Give Permissio and Run Patch
      run: |
        chmod +x ${{ github.event.inputs.ARCHITECTURE }}/vbmeta-disable-verification
        ./${{ github.event.inputs.ARCHITECTURE }}/vbmeta-disable-verification vbmeta.img

    - name: Upload to Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: vbmeta.img
        Name: Patched VBMeta
        draft: false
        prerelease: true
        tag: ${{ github.run_id }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          Your vbmeta image are now ready!
          Flash it now.

    - name: Link to Release
      run: |
        echo "https://github.com/${GITHUB_REPOSITORY}/releases/tag/${{ github.run_id }}"
